config/routes.rb
Rails.application.routes.draw do
  #get 'home/zipcode'
  root 'home#index'
  post "zipcode" => 'home#zipcode'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	require 'net/http'
  	require 'json'
  	#@url ='http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=20002&distance=0&API_KEY=42663F16-C7B4-4016-995E-7E397DC531B1'
  	@url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=20002&distance=0&API_KEY=42663F16-C7B4-4016-995E-7E397DC531B1'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@output = JSON.parse(@response)
  #check for empty string
  	if @output.empty?
  		@final_output = "Error"
  	elsif !@output
  		@final_output = "Error"  				
  	else
  		@final_output=@output[0]['AQI']
  	end	

  	if @final_output=="Error"
  		@api_color = "gray"
  		@api_description = "No zip code found!"
  	elsif @final_output<=50
  		@api_color = "green"
  		@api_description = "AQI: Good (0 - 50)"
  	elsif @final_output>=51 && @final_output<=100
  		@api_color = "yellow"
  		@api_description = "AQI: Moderate (51 - 100)"
  	elsif @final_output>=101 && @final_output<=150
  		@api_color = "orange"
  		@api_description = "AQI: Unhealthy for Sensitive Groups (101 - 150)"
  	elsif @final_output>=151 && @final_output<=200
  		@api_color = "red"
  		@api_description = "AQI: Unhealthy (151 - 200) "
  	elsif @final_output>=201 && @final_output<=300
  		@api_color = "purple"
  		@api_description = "AQI: Very Unhealthy (201 - 300)"
  	elsif @final_output>=301 && @final_output<=500
  		@api_color = "maroon"
  		@api_description = "AQI: Hazardous (301 - 500)"							
  		
  	end
  end
  def zipcode
  	@zipquery = params[:zipcode]
  	if params[:zipcode] == ""
  		@zipquery="Zipcode cannot be empty!"
  	elsif params[:zipcode]
  			
		require 'net/http'
  	require 'json'
  	#@url ='http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=20002&distance=0&API_KEY=42663F16-C7B4-4016-995E-7E397DC531B1'
  	@url = 'http://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zipquery.to_s+ '&distance=0&API_KEY=42663F16-C7B4-4016-995E-7E397DC531B1'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@output = JSON.parse(@response)
  #check for empty string
  	if @output.empty?
  		@final_output = "Error"
  	elsif !@output
  		@final_output = "Error"  				
  	else
  		@final_output=@output[0]['AQI']
  	end	

  	if @final_output=="Error"
  		@api_color = "gray"
  		@api_description = "No zip code found!"
  	elsif @final_output<=50
  		@api_color = "green"
  		@api_description = "AQI: Good (0 - 50)"
  	elsif @final_output>=51 && @final_output<=100
  		@api_color = "yellow"
  		@api_description = "AQI: Moderate (51 - 100)"
  	elsif @final_output>=101 && @final_output<=150
  		@api_color = "orange"
  		@api_description = "AQI: Unhealthy for Sensitive Groups (101 - 150)"
  	elsif @final_output>=151 && @final_output<=200
  		@api_color = "red"
  		@api_description = "AQI: Unhealthy (151 - 200) "
  	elsif @final_output>=201 && @final_output<=300
  		@api_color = "purple"
  		@api_description = "AQI: Very Unhealthy (201 - 300)"
  	elsif @final_output>=301 && @final_output<=500
  		@api_color = "maroon"
  		@api_description = "AQI: Hazardous (301 - 500)"							
  		
  	end  			





















  		
  	end
  end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Ozone WebApp", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
      </li>
      
    </ul>
    <%= form_tag zipcode_path, :method => 'POST' do %>
    <div class="form-inline my-2 my-lg-0">
      <%= text_field_tag 'zipcode', nil, placeholder: "Search Zipcode" , class: "form-control mr-sm-2" %>
      <%= submit_tag 'Search' , class: 'btn btn-outline-success my-2 my-sm-0'  %>
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p>This is the current Air Quality Index (AQI)</p>
  <p><%= @api_description %></p>
  <p>Hit reload to update the readings.</p>
</div>

</br>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%= @final_output %></h1>
  <p>This is the current Air Quality Index (AQI) of Zipcode: <%= @zipquery %></p>
  <p><%= @api_description %></p>
  <p>Hit reload to update the readings.</p>
</div>

</br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'home/navbar' %>
  	<div class="container">
    	</br>
    	<%= yield %>
	</div>
  </body>
</html>